/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;


public class IngresarReserva extends javax.swing.JFrame {

    /**
     * Creates new form IngresarReserva
     */
    public IngresarReserva() {
        initComponents();
        
        setExtendedState(IngresarReserva.MAXIMIZED_BOTH);
        
        cargarPaises();
        
        jComboBoxPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    String paisSeleccionado = (String) jComboBoxPais.getSelectedItem();
                    cargarCiudades(paisSeleccionado);
                }
            }
        });
        
        
    }


    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboCiudad = new javax.swing.JComboBox<>();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelAvion = new javax.swing.JLabel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jComboBoxPais = new javax.swing.JComboBox<>();
        jButtonIngresarR = new javax.swing.JButton();
        jLabelPais = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 370, -1));

        jLabelCiudad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCiudad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCiudad.setText("Ciudad:");
        getContentPane().add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, -1, -1));

        jLabelAvion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(jLabelAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, -30, 500, 490));

        jLabelIdUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdUsuario.setText("ID USUARIO:");
        getContentPane().add(jLabelIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, -1));

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 370, -1));

        jComboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, 370, -1));

        jButtonIngresarR.setBackground(new java.awt.Color(0, 0, 153));
        jButtonIngresarR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonIngresarR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresarR.setText("Registrar Reserva");
        jButtonIngresarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 680, 220, 50));

        jLabelPais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPais.setText("Pais:");
        getContentPane().add(jLabelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(0, 0, 153));
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("<--");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 153));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("X");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HD Desktop Blue206572979.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed

        Principal Principal = new Principal();

        Principal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    
    
    
    
    
    private void cargarPaises(){
       String url = "jdbc:oracle:thin:@localhost:1521:orcl";
       String usuario = "proyecto";
       String contrasena = "proyecto"; 
              
       try (Connection conn = DriverManager.getConnection(url, usuario, contrasena)) {
        String sql = "SELECT DISTINCT PAIS FROM DESTINO";
        try (PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            // Limpiar el modelo actual del ComboBox
            jComboBoxPais.setModel(new DefaultComboBoxModel());

            // Agregar los países al ComboBox
            while (rs.next()) {
                String pais = rs.getString("PAIS");
                jComboBoxPais.addItem(pais);
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Manejar la excepción según sea necesario
    }
       
       
    }
    
    private void cargarCiudades(String paisSeleccionado) {
    String url = "jdbc:oracle:thin:@localhost:1521:orcl";
    String usuario = "proyecto";
    String contrasena = "proyecto";

    try (Connection conn = DriverManager.getConnection(url, usuario, contrasena)) {
        String sql = "SELECT CIUDAD_DESTINO FROM DESTINO WHERE PAIS = ?";
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, paisSeleccionado);
            try (ResultSet rs = pstmt.executeQuery()) {

                // Limpiar el modelo actual del ComboBox
                jComboCiudad.setModel(new DefaultComboBoxModel());

                // Agregar las ciudades al ComboBox
                while (rs.next()) {
                    String ciudad = rs.getString("CIUDAD_DESTINO");
                    jComboCiudad.addItem(ciudad);
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Manejar la excepción según sea necesario
    }
}
    
    private void jButtonIngresarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarRActionPerformed
     // Obtener la ciudad seleccionada
    String ciudadSeleccionada = (String) jComboCiudad.getSelectedItem();

    // Obtener el ID del cliente ingresado
    String idCliente = jTextFieldUsuario.getText();

    // Validar que se haya seleccionado una ciudad y que se haya ingresado un ID de cliente
    if (ciudadSeleccionada != null && !ciudadSeleccionada.isEmpty() && idCliente != null && !idCliente.isEmpty()) {
        // Ejecutar la consulta SQL para obtener el ID del vuelo y el precio de la tabla "DESTINO"
        String url = "jdbc:oracle:thin:@localhost:1521:orcl";
        String usuario = "proyecto";
        String contrasena = "proyecto";

        try (Connection conn = DriverManager.getConnection(url, usuario, contrasena)) {
            String sql = "SELECT ID_VUELO, PRECIO FROM DESTINO WHERE CIUDAD_DESTINO = ?";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, ciudadSeleccionada);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        // Obtener el ID del vuelo y el precio
                        int idVuelo = rs.getInt("ID_VUELO");
                        double precio = rs.getDouble("PRECIO");

                        // Ejecutar la consulta SQL para insertar los datos en la tabla "RESERVA"
                        sql = "INSERT INTO RESERVA (DESTINO, ID_CLIENTE, ID_VUELO, PRECIO) VALUES (?, ?, ?, ?)";
                        try (PreparedStatement pstmt2 = conn.prepareStatement(sql)) {
                            pstmt2.setString(1, ciudadSeleccionada);
                            pstmt2.setString(2, idCliente);
                            pstmt2.setInt(3, idVuelo);
                            pstmt2.setDouble(4, precio);

                            int filasInsertadas = pstmt2.executeUpdate();
                            System.out.println("Se insertaron " + filasInsertadas + " filas en la tabla RESERVA.");

                            // Mostrar un mensaje de éxito
                            JOptionPane.showMessageDialog(this, "Reserva ingresada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } else {
                        // Mostrar un mensaje de error si no se encontró la ciudad en la tabla DESTINO
                        JOptionPane.showMessageDialog(this, "La ciudad seleccionada no tiene vuelos disponibles", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Manejar la excepción según sea necesario
        }
    } else {
        // Mostrar un mensaje de error si no se seleccionó una ciudad o no se ingresó un ID de cliente
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una ciudad y especifique el ID de cliente", "Error", JOptionPane.ERROR_MESSAGE);
    }
    jTextFieldUsuario.setText("");
    }//GEN-LAST:event_jButtonIngresarRActionPerformed

    private void jComboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaisActionPerformed
        
    }//GEN-LAST:event_jComboBoxPaisActionPerformed

    private void jComboCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresarR;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxPais;
    private javax.swing.JComboBox<String> jComboCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAvion;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
