/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
public class IngresarClientes extends javax.swing.JFrame {

    /**
     * Creates new form IngresarClientes
     */
    public IngresarClientes() {
        initComponents();
        setExtendedState(IngresarClientes.MAXIMIZED_BOTH);              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIngresar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelProvincia = new javax.swing.JLabel();
        jLabelCanton = new javax.swing.JLabel();
        jLabelDireccion1 = new javax.swing.JLabel();
        jTextFieldDireccion1 = new javax.swing.JTextField();
        jLabelDireccion2 = new javax.swing.JLabel();
        jTextFieldDireccion2 = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelAvion = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jComboBoxProvincia = new javax.swing.JComboBox<>();
        jTextFieldCanton = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Registrar usuario");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 750, 220, 50));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 370, -1));

        jLabelApellido1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelApellido1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido1.setText("Primer apellido:");
        getContentPane().add(jLabelApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 370, -1));

        jLabelApellido2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelApellido2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido2.setText("Segundo apellido:");
        getContentPane().add(jLabelApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, -1, -1));

        jTextFieldApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 370, -1));

        jLabelSexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Genero:");
        getContentPane().add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, -1, 30));

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha de nacimiento:");
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, -1, 20));

        jLabelCelular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCelular.setText("Numero de contacto:");
        getContentPane().add(jLabelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 770, -1, 30));

        jTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCelularActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 780, 370, -1));

        jLabelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo:");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 830, -1, 30));

        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 840, 370, -1));

        jLabelProvincia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProvincia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProvincia.setText("Provincia:");
        getContentPane().add(jLabelProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, -1, 20));

        jLabelCanton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCanton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCanton.setText("Cantón:");
        getContentPane().add(jLabelCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 500, -1, 30));

        jLabelDireccion1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDireccion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion1.setText("Direccion 1:");
        getContentPane().add(jLabelDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, -1, 30));

        jTextFieldDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccion1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 560, 370, -1));

        jLabelDireccion2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDireccion2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion2.setText("Direccion 2:");
        getContentPane().add(jLabelDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 600, -1, 30));

        jTextFieldDireccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccion2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 610, 370, -1));

        jLabelDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("Descripción:");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 650, -1, 30));

        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 660, 370, -1));

        jButtonVolver.setBackground(new java.awt.Color(0, 0, 153));
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("<--");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 153));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("X");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, 50, -1));

        jLabelAvion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(jLabelAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, -30, 500, 490));

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "M", "F", "O" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 370, 30));

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "San Jose", "Heredia", "Alajuela", "Cartago", "Guanacaste", "Puntarenas", "Limón" }));
        jComboBoxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProvinciaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 460, 370, -1));
        getContentPane().add(jTextFieldCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 510, 370, -1));
        getContentPane().add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 370, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HD Desktop Blue206572979.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed

        Principal Principal = new Principal();

        Principal.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed

    private void jTextFieldApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido2ActionPerformed

    private void jTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCelularActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void jTextFieldDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccion1ActionPerformed

    private void jTextFieldDireccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccion2ActionPerformed

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    
    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
       
        String url = "jdbc:oracle:thin:@localhost:1521:orcl";
        String usuario = "proyecto";
        String contrasena = "proyecto";

        String nombre = jTextFieldNombre.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        String sexo = (String) jComboBoxGenero.getSelectedItem();
        //String fecha = jTextFieldFecha.getText();
        java.util.Date fecha2 = jDateChooser.getDate();
        java.sql.Date fechaSQL = new java.sql.Date(fecha2.getTime());
        String celular = jTextFieldCelular.getText();
        String correo = jTextFieldCorreo.getText();
        String provincia = (String) jComboBoxProvincia.getSelectedItem();
        String canton = jTextFieldCanton.getText();
        int idCanton;
        String direccion1 = jTextFieldDireccion1.getText();
        String direccion2 = jTextFieldDireccion2.getText();
        String descripcion = jTextFieldDescripcion.getText();
              
        String cantonLowerCase = canton.toLowerCase();

            switch (cantonLowerCase) {
                case "santo domingo":
                idCanton = 46;
                break;
                case "heredia":
                idCanton = 44;
                break;
                case "barva":
                idCanton = 45;
                break;  
                case "santa barbara":
                idCanton = 47;
                break;
                case "san rafael":
                idCanton = 48;
                break;
                case "san isidro":
                idCanton = 49;
                break;
                case "belen":
                idCanton = 50;
                break;
                case "flores":
                idCanton = 51;
                break;
                case "san pablo":
                idCanton = 52;
                break;
                case "sarapiquí":
                idCanton = 53;               
                break;
                case "san jose":
                idCanton = 1;               
                break;
                case "escazu":
                idCanton = 2;               
                break;
                case "desamparados":
                idCanton = 3;               
                break;
                case "puriscal":
                idCanton = 4;               
                break;
                case "tarrazu":
                idCanton = 5;               
                break;
                case "aserri":
                idCanton = 6;               
                break;
                case "mora":
                idCanton = 7;               
                break;
                case "goicoechea":
                idCanton = 8;               
                break;
                case "santa ana":
                idCanton = 9;               
                break;
                case "alajuelita":
                idCanton = 10;   
                break;
                case "alajuela":
                idCanton = 21; 
                break;
                case "san Ramón":
                idCanton = 22; 
                break;
                case "grecia":
                idCanton = 23; 
                break;
                case "san mateo":
                idCanton = 24; 
                break;
                case "atenas":
                idCanton = 25; 
                break;
                case "naranjo":
                idCanton = 26; 
                break;
                case "palmares":
                idCanton = 27; 
                break;
                case "poas":
                idCanton = 28; 
                break;
                case "orotina":
                idCanton = 29; 
                break;
                case "san marlos":
                idCanton = 30; 
                break;
                case "cartago":
                idCanton = 36; 
                break;
                case "paraiso":
                idCanton = 37; 
                break;
                case "la union":
                idCanton = 38; 
                break;
                case "jimenez":
                idCanton = 39; 
                break;
                case "turrialba":
                idCanton = 40; 
                break;
                case "alvarado":
                idCanton = 41; 
                break;
                case "oreamundo":
                idCanton = 42; 
                break;
                case "san carlos ":
                idCanton = 43; 
                break;
                case "el guarco":
                idCanton = 44; 
                break;
                case "liberia":
                idCanton = 54; 
                break;
                case "nicoya":
                idCanton = 55; 
                break;
                case "santa cruz":
                idCanton = 56; 
                break;
                case "bagaces":
                idCanton = 57; 
                break;
                case "carrillo":
                idCanton = 58; 
                break;
                case "cañas":
                idCanton = 59; 
                break;
                case "abangares":
                idCanton = 60; 
                break;
                case "tilaran":
                idCanton = 61; 
                break;
                case "nandayure":
                idCanton = 62; 
                break;
                case "la cruz":
                idCanton = 63; 
                break;
                case "puntarenas":
                idCanton = 65;
                break;
                case "esparza":
                idCanton = 66;
                break;
                case "buenos aires":
                idCanton = 67;
                break;
                case "montes de oro":
                idCanton = 68;
                break;
                case "osa":
                idCanton = 69;
                break;
                case "quepos":
                idCanton = 70;
                break;
                case "golfito":
                idCanton = 71;
                break;
                case "limon":
                idCanton = 98;
                break;
                case "pococi":
                idCanton = 99;
                break;
                case "siquirres":
                idCanton = 100;
                break;
                case "matina":
                idCanton = 101;
                break;
                case "guacimo":
                idCanton = 102;
                break;
                default:
                idCanton = -1;
                break;
            }

        try (Connection conn = DriverManager.getConnection(url, usuario, contrasena)) {
    // Verificar si el correo ya está en uso
    String sqlVerificarCorreo = "SELECT COUNT(*) FROM cliente WHERE CORREO = ?";
    try (PreparedStatement pstmtVerificarCorreo = conn.prepareStatement(sqlVerificarCorreo)) {
        pstmtVerificarCorreo.setString(1, correo);
        try (ResultSet rs = pstmtVerificarCorreo.executeQuery()) {
            if (rs.next() && rs.getInt(1) > 0) {
                // El correo ya está en uso, mostrar mensaje y salir del método
                JOptionPane.showMessageDialog(this, "Usuario ya registrado", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                // Insertar domicilio
                String sqlInsertDomicilio = "INSERT INTO domicilio (DIRECCION1, DIRECCION2, DESCRIPCION) VALUES (?, ?, ?)";
                try (PreparedStatement pstmtInsertDomicilio = conn.prepareStatement(sqlInsertDomicilio)) {
                    pstmtInsertDomicilio.setString(1, direccion1);
                    pstmtInsertDomicilio.setString(2, direccion2);
                    pstmtInsertDomicilio.setString(3, descripcion);

                    int filasInsertadasDomicilio = pstmtInsertDomicilio.executeUpdate();
                    System.out.println("Se insertaron " + filasInsertadasDomicilio + " filas en la tabla domicilio.");
                }

                // Insertar cliente
                String sqlInsertCliente = "INSERT INTO cliente (NOMBRE, PRIM_APELLIDO, SEG_APELLIDO, SEXO, FECHNACIMIENTO, NUMERO_CONTACTO, CORREO, ID_CIUDADP) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                try (PreparedStatement pstmtInsertCliente = conn.prepareStatement(sqlInsertCliente)) {
                    pstmtInsertCliente.setString(1, nombre);
                    pstmtInsertCliente.setString(2, apellido1);
                    pstmtInsertCliente.setString(3, apellido2);
                    pstmtInsertCliente.setString(4, sexo);
                    //pstmtInsertCliente.setString(5, fecha);
                    pstmtInsertCliente.setDate(5, fechaSQL);
                    pstmtInsertCliente.setString(6, celular);
                    pstmtInsertCliente.setString(7, correo);
                    pstmtInsertCliente.setInt(8, idCanton);

                    int filasInsertadasCliente = pstmtInsertCliente.executeUpdate();
                    System.out.println("Se insertaron " + filasInsertadasCliente + " filas en la tabla cliente.");
                }

                JOptionPane.showMessageDialog(this, "Usuario ingresado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

                jTextFieldNombre.setText("");
                jTextFieldApellido1.setText("");
                jTextFieldApellido2.setText("");
                jTextFieldCelular.setText("");
                jTextFieldCorreo.setText("");
                jTextFieldDireccion1.setText("");
                jTextFieldDireccion2.setText("");
                jTextFieldDescripcion.setText("");
                jTextFieldCanton.setText("");
                jComboBoxProvincia.setSelectedIndex(-1);
                jComboBoxGenero.setSelectedIndex(-1);
                jDateChooser.setDate(null); 
                
            }
        }
    }
} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error al verificar el correo", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jComboBoxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProvinciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxProvincia;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelAvion;
    private javax.swing.JLabel jLabelCanton;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDireccion1;
    private javax.swing.JLabel jLabelDireccion2;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCanton;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldDireccion1;
    private javax.swing.JTextField jTextFieldDireccion2;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
